services:
  db:
    image: mariadb:10.6.9
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: qwer4321
    command: |
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --default-authentication-plugin=mysql_native_password
    volumes:
      - mariadb-data-volume:/var/lib/mysql
      - ./docker/db:/docker-entrypoint-initdb.d

  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    command: |
      bash -c
      "yarn install --check-files && \
       bundle install && \
       rake db:migrate && \
       rm -f tmp/pids/server.pid && \
       ./bin/dev"
    stdin_open: true
    tty: true
    volumes:
      - .:/usr/src/app
      - ~/.ssh:/root/.ssh:ro
      - bundle-volume:/usr/local/bundle
    ports:
      - 3000:3000
      - 1234:1234
    environment:
      - HUB_URL=http://chrome:4444/wd/hub
    depends_on:
      - db
      - chrome

  chrome:
    # ARM cpu use this image seleniarm/standalone-chromium:latest
    image: seleniarm/standalone-chromium:latest
    volumes:
      - /dev/shm:/dev/shm
    environment:
      - JAVA_OPTS=-Dwebdriver.chrome.whitelistedIps=
    ports:
      - '5900:5900'

#Volumes
volumes:
  bundle-volume:
  mariadb-data-volume:
